config/routes.rb
BH::Application.routes.draw do

 resources :password_resets

  root :to => 'catalog#index'

  match 'catalog' => 'catalog#index'
  match 'admin/glasses' => 'admin/glasses#index'
  match 'about' => 'about#index'  
  match 'checkout' => 'checkout#index'
  match 'admin/manufacturer' => 'admin/manufacturer#index'
  match 'admin/order' => 'admin/order#index'
  match 'forum' => 'forum#index'
  
  get 'admin/manufacturer/new'
  post 'admin/manufacturer/create'
  get 'admin/manufacturer/edit'
  post 'admin/manufacturer/update'
  post 'admin/manufacturer/destroy'
  get 'admin/manufacturer/show'
  match 'admin/manufacturer/show/:id' => 'admin/manufacturer#show'
  get 'admin/manufacturer/index'

  get 'admin/glasses/new'
  post 'admin/glasses/create'
  get 'admin/glasses/edit'
  post 'admin/glasses/update'
  post 'admin/glasses/destroy'
  get 'admin/glasses/show'
  match 'admin/glasses/show/:id' => 'admin/glasses#show'
  get 'admin/glasses/index'
  
  get 'catalog/show'
  match 'catalog/show/:id' => 'catalog#show'
  get 'catalog/index'
  get 'catalog/latest'
  get 'catalog/rss'
  get 'catalog/search'
  match 'catalog/search/:q' => 'catalog/search#search'
  
  get 'cart/add'
  post 'cart/add'
  get 'cart/remove'
  post 'cart/remove'
  get 'cart/clear'
  post 'cart/clear'
  
  post 'admin/order/close'
  get 'admin/order/show'
  match 'admin/order/show/:id' => 'admin/order#show'
  get 'admin/order/index'
  post 'admin/order/destroy'

  get 'checkout/index'
  post 'checkout/submit_order'
  get 'checkout/thank_you'

  get 'user_session/new'
  post 'user_session/create'
  get 'user_session/destroy'

  get 'user/new'
  post 'user/create'
  get 'user/show'
  match 'user/show/:id' => 'user#show'
  get 'user/edit'
  post 'user/update'

  get "forum/index"
  get "forum/reply"
  match 'forum/reply/:id'  => 'forum#reply'
  get "forum/show"
  get "forum/list"
  match 'forum/show/:id' => 'forum#show'
  get "forum/post"
  post "forum/create"
  match 'forum/create/:id' => 'forum#create'
  get 'forum/destroy'
  match 'forum/destroy/:id' => 'forum#destroy'

   

  

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  logout_on_timeout true # default if false
end

app/controllers/user_session_controller.rb
# encoding: UTF-8

class UserSessionController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]

  def new
    @user_session = UserSession.new
    @page_title = 'Iniciar sesión'
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    @user_session.remember_me = false # just in case
    if @user_session.save
      flash[:notice] = "Sesión iniciada."
      redirect_back_or_default :controller => '/admin/manufacturer', :action => :index # default login route
    else
      render :action => :new
    end
  end

  def destroy
    if current_user_session # only for an authenticated user
      current_user_session.destroy
      flash[:notice] = "Sesión cerrada."
    end  
    redirect_to :controller => :catalog, :action => :index # logout route
  end
end

app/views/user_session/_form.html.erb
<% if @user_session.errors.any? %>
  <div id="errorExplanation">
  <h2><%= pluralize(@user_session.errors.count, "error", "errores") %> impiden al usuario su acceso identificado:</h2>
    <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <p><label for="login">Cuenta de usuario</label><br/>
  <%= text_field 'user_session', 'login' %></p>
</div>

<div class="field">
  <p><label for="password">Clave de acceso</label><br/>
  <%= password_field 'user_session', 'password' %></p>
</div>
<div class="field">
  <p><%= link_to "Olvidó su contraseña?", new_password_reset_path %></p>
</div>
<!-- <div class="check_box">
  <p><label for="remember_me">Remember me</label><br/>
  <%= check_box 'user_session', 'remember_me' %></p>
</div> -->

app/views/user_session/new.html.erb
<%= form_tag :action => 'create' do %>   
  <%= render :partial => 'form' %>   
  <%= submit_tag 'Iniciar sesión' %>
<% end %>